let pos_neg ={
    "neg_1":[
        "./Images/neg_1_claws",
    ],
    "neg_2":[   
        "./Images/neg_2_morty",
    ],
    "neg_3":[
        "./Images/neg_3_sun",
    ],
    "neg_4":[    
        "./Images/neg_4_larry",
    ],    
    "neg_5":[    
        "./Images/neg_5_larry_2",
    ],    
    "neg_6":[    
        "./Images/neg_6_claws",
    ],    
    "neg_7":[    
        "./Images/neg_7_rick_morty",
    ],    
    "neg_8":[    
        "./Images/neg_8_snowball",
    ],

    "pos_1":[    
        "./Images/pos_1_getschwifty",
    ],    
    "pos_2":[    
        "./Images/pos_2_mrmeeseeks",
    ],
    "pos_3":[    
        "./Images/pos_3_portal",
    ],    
    "pos_4":[    
        "./Images/pos_4_luva",
    ],
    "pos_5":[    
        "./Images/pos_5_Squanchy",
    ],    
    "pos_6":[    
        "./Images/pos_6_butthole",
    ],    
    "pos_7":[    
        "./Images/pos_7_dance",
    ],    
    "pos_8":[    
        "./Images/pos_8_pickle",
    ]
}
let sound ={
    ""
}